import type { Metadata } from "next";
import "./globals.css";
import StyledJsxRegistry from "./registry";
import { Suspense } from "react";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";
import {AOSInit} from './aos';
import SessionWrapper from "./provider/SessionWrapper ";
import MainProvider from "./provider/MainProvider";
import { sfpro } from "./font";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
        <SessionWrapper>
        <body className="bg-backgroundWhiteSmoke">
          <MainProvider>
              <AOSInit/>
                <StyledJsxRegistry>
                  <Suspense fallback>
                      <ErrorBoundary errorComponent={Error}>{children}</ErrorBoundary>
                   </Suspense>
              </StyledJsxRegistry>
          </MainProvider>
        </body>
        </SessionWrapper>
      </html>
    // </SessionWrapper>
  );
}
